### ISSUE TITLE
Error message tidak benar

### ISSUE THREAD

**Issue by azemoning** [nandanugg/LearnRESTMiddlewarePagi#1]
![Screen Shot 2021-02-05 at 09 57 41](https://user-images.githubusercontent.com/37897882/106983509-96f10580-6798-11eb-827c-796313ce1aa8.png)

@nandanugg

**Comment by nandanugg** [comment]
Ini udah fix di #2d7befd

@nandanugg

**Comment by nandanugg** [comment]
Ini udah aku fix disini [disini](https://github.com/nandanugg/LearnRESTMiddlewarePagi/commit/2d7befd2fbc0466fe95f09b402b1a5ac0215a609)

@nandanugg

**Comment by nandanugg** [comment]
LGTM
